# config.py
import numpy as np

# World Configuration
WORLD_WIDTH = 1000
WORLD_HEIGHT = 1000
MAX_PROBES = 20
INITIAL_PROBES = 3

# Resource Configuration
RESOURCE_COUNT = 30
RESOURCE_MIN_AMOUNT = 50
RESOURCE_MAX_AMOUNT = 200
RESOURCE_REGEN_RATE = 0.01  # units per step
HARVEST_RATE = 2.0
HARVEST_DISTANCE = 20

# Probe Configuration
MAX_ENERGY = 100
INITIAL_ENERGY = 50
REPLICATION_COST = 40
REPLICATION_MIN_ENERGY = 60
MAX_VELOCITY = 5.0
THRUST_POWER = [0, 1, 2]
ENERGY_DECAY_RATE = 0.01

# Communication
COMM_RANGE = 100
MESSAGE_TYPES = ['RESOURCE_LOCATION']

# Training Configuration
EPISODE_LENGTH = 5000
LEARNING_RATE = 3e-4
BATCH_SIZE = 64

# Visualization
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
FPS = 60